---
title: "Untitled"
output: html_document
date: "2023-01-10"
---


```{r message=FALSE}

library(tidyverse)
library(here)
library(visdat)
library(DataExplorer)
library(skimr)
library(tidytext)

here::i_am("analysis.Rmd")

```



### Read Data


```{r}
data <- read_csv(here("processed", "GTI_2012-2021.csv"))
```


### Explore Data


```{r}
glimpse(data)

```



```{r}
head(data)
```



```{r}
data %>%
  group_by(year, ranking) %>%
  tally()
```



```{r}
data %>%
  group_by(year, continent) %>%
  tally()
```



```{r}
summary(data)
```


```{r}
data %>%
  arrange(desc(year)) %>%
  vis_dat()
```


```{r}
data %>%
  get_dupes()
```



```{r}
data %>%
  skim()
```


```{r}
create_report(data)
```




```{r}
data %>%
  filter(year == 2021) %>%
  ggplot( aes(x = ranking)) +
    geom_histogram( alpha=0.6, position = 'identity', fill = "#7C85A6", color = "#474E68", binwidth = 5) +
    labs(y = "Frequency",
         x = "Ranking",
         title = "Rankings 2021") +
theme_minimal() +
    theme(
    axis.text.x = element_text(colour = "#3B4157", size = 14),
    axis.title.x = element_text(colour = "#3B4157", size = 14),
    axis.text.y = element_text(colour = "#3B4157", size = 14),
    axis.title.y = element_text(colour = "#3B4157", size = 14),
    panel.grid = element_blank(),
    plot.title = element_text(colour = "#3B4157",
                              size = 18,
                              margin = margin(b= 20)),
    legend.position="none",
    plot.title.position = "plot")
```



```{r}
data %>%
  filter(year == 2021,
         ranking <= 20) %>%
  arrange(desc(ranking)) %>%
  ggplot(aes(x = country, y = total)) +
  geom_bar(position="dodge", stat="identity") + 
  # geom_text(
  #   aes(label = value),
  #   size = 5,
  #   vjust = 1.5, # position = position_dodge(.9),
  #   color = "#fff7fb"
  # ) +
  #scale_fill_manual(values = c("#474E68", "#7C85A6")) +
  labs(x = "",
       y = "",
       title = "Maximale und mittlere Personenzahl/Tag") +
  coord_flip() +
  theme_minimal() +
  theme(
    #axis.line.y=element_blank(),
    #axis.text.y=element_blank(),
    axis.text.x = element_text(colour = "#3B4157", size = 14),
    panel.grid = element_blank(),
    plot.title = element_text(colour = "#3B4157",
                              size = 18,
                              margin = margin(b= 20)),
    legend.position="none",
    plot.title.position = "plot"
)

```




```{r}
data %>%
  filter(year == 2021,
         ranking <= 20) %>%
  #arrange(country) %>%
  mutate(ranking = as.factor(ranking),
        # country = fct_reorder(country, total), #) %>%
          country = reorder_within(country, total, ranking)) %>%
  ggplot(aes(x=country, y=total)) +
  geom_segment( aes(x=country, xend=country, y=0, yend=total)) +
  geom_point(size=4, alpha=0.6) +
  theme_minimal() +
  coord_flip() +
  #scale_x_reordered() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )
```



```{r}
glimpse(data)
```






