---
title: "Untitled"
output: html_document
date: "2023-01-10"
---


```{r message=FALSE}
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(countrycode)
library(jsonlite)
library(sf)

here::i_am("analysis.Rmd")

```



### Read Data


```{r}
original_data_2012_2021 <- read_xlsx(here("original","GTI_2012-2021.xlsx"))

```


```{r}
glimpse(original_data_2012_2021)
```



### Clean Data


```{r}
data_2012_2021 <- original_data_2012_2021 %>%
    # pivot_longer(`Antidiscrimination Legislation`:`Conversion Therapy`, "indicator", "value") %>%
  clean_names(case = "lower_camel") %>%
  rename("transgenderRights" = "transGenderRights") 

```



### Add 2023 data (see "pdfScraping.Rmd)


```{r}
data_2023 <- read_csv(here("processed","GTI_2023.csv"))

```



```{r}
data_2012_2023 <- bind_rows(data_2012_2021, data_2023)
```




### Add Continents


```{r}
data <- data_2012_2023 %>%
  # mutate(across(c(where(is.numeric)),
  #              factor)) %>%
  mutate(country = case_when(
   country == "Central African Republic" ~ "Central African Rep.",
    country == "China/Hong Kong" ~ "China incl. Hong Kong",
    country == "Dem.Rep. of Congo" ~ "Dem. Rep. of Congo",
    country == "Georgia (Europe)" ~ "Georgia",
    country == "Macedonia" ~ "North Macedonia",
    country == "USA*" ~ "United States of America",
    # country == "Virgin Islands (USA)" ~ "Virgin Islands (USA)",
    country == "Virgin Islands" ~ "Virgin Islands (USA)",
   country == "United States Virgin Islands" ~ "Virgin Islands (USA)",
   country == "Rep. of the Congo" ~ "Republic of the Congo",
    country == "Saint Maarten" ~ "Sint Maarten",
    country == "Bosnia-Hercegovina" ~ "Bosnia and Herzegovina",
    country == "Moldovia" ~ "Moldova",
    country == "Maledives" ~ "Maldives",
   # country == "Antigua & Barbuda" ~ "Antigua and Barbuda",
    country == "Bosnia-Herzegovina" ~ "Bosnia and Herzegovina",
    country == "Cabo Verde" ~ "Cape Verde",
    #country == "China incl. Hong Kong" ~ "People's Republic of China",
    country == "Comoros Islands" ~ "Comoros",
   # country == "Dem. Rep. of Congo" ~ "Democratic Republic of the Congo",
    country == "Gambia" ~ "The Gambia",
    country == "Korea South" ~ "South Korea",
    country == "Curacao" ~ "Curaçao",
    country == "St. Maarten" ~ "Sint Maarten",
    country == "USA" ~ "United States of America",
    #country == "Trinidad & Tobago" ~ "Trinidad and Tobago",
    country == "Korea North" ~ "North Korea",
    country == "USA" ~ "United States of America",
    country == "Bahamas" ~ "The Bahamas",
    country == "Macao" ~ "Macau",
    country == "Swaziland" ~ "Eswatini",
    TRUE ~ country
  )) %>%
    mutate(longName = case_when(
    country == "Central African Rep." ~ "Central African Republic",
    country == "China incl. Hong Kong" ~ "People's Republic of China",
    country =="Dem. Rep. of Congo" ~ "Democratic Republic of the Congo",
    # country == "Virgin Islands (USA)" ~ "United States Virgin Islands",
    country == "Rep. of the Congo" ~ "Republic of the Congo",
    country == "Antigua & Barbuda" ~ "Antigua and Barbuda",
    country == "Trinidad & Tobago" ~ "Trinidad and Tobago",
    TRUE ~ country
  )) %>%
  filter(country != "Bonaire" & country != "Saint Kitts & Nevis") %>%
  mutate(continent = countrycode(country, "country.name.en", "continent")) %>%
  mutate(continent = case_when(
    country == "Kosovo" ~ "Europe",
    #country == "United States Virgin Islands" ~ "Americas",
    country == "Virgin Islands (USA)" ~ "Americas",
    country == "Chechnya" ~ "Europe",
   # country == "Bonaire" ~ "Americas",
    country == "Maledives" ~ "Asia",
    TRUE ~ continent
  )) %>%
  relocate(continent, .after = country)
  
# Bonaire and Saint Kitts & Nevis in 2012, 2013, 2014 only
```





```{r}
countries2023 <- data %>%
  filter(year == 2023) %>%
  distinct(country) %>%
  pull()

countries2023
```



```{r}
data %>%
  filter(!country %in% countries2023) %>%
  distinct(country)

# data cleaning above
```





```{r}
summary(data)

```


### seperate dataset for 2023


```{r}
data2023 <- toJSON(as_tibble(data %>% filter(year == 2023)))
```




### Save data


```{r}
write_csv(data, here("processed/GTI_2012-2023.csv"))
```




```{r}
dataJSON <- toJSON(data)
```



```{r}
write(dataJSON, here("processed/GTI_2012-2023.json"))
```


```{r}
write(data2023, here("processed/GTI_2012-2023_data2023.json"))
```







### Geographical Data

check names and adjust or add variable above in data


```{r}
# geo <- st_read(here("original", 
#                     "ne_110m_admin_0_countries",
#                     "ne_110m_admin_0_countries.shp")) %>%
#   clean_names() %>%
#   select(c("name", "name_long", "name_en", "geometry")) %>%
#   arrange(name)
```


```{r}
# geo_data <- data %>%
#   left_join(geo, by = c("country" = "name_en")) %>%
#   relocate(name:name_long, .after = country)
```


```{r}
# geo_data %>%
#   filter(is.na(name)) %>%
#   distinct(country)

# Guadeloupe (France), Reunion (France), Martinique (France), Indonesia/Aceh (Indonesia), Chechnya (Russia), Gibraltar
```







